version: '3.8'

services:
  backend:
    build:
      context: ../

  web:
    build:
      context: ../
    environment:
      env: ../env.local

  mobile:
    build:
      context: ../
    environment:
      env: ../env.local





